### ISSUE TITLE
sync from openshift

### ISSUE THREAD

**Issue by zfrhv** [redhat-cop/group-sync-operator#107]
im trying to sync groups to openshift from rhsso. 
i deployed the oprator from helm chart. 
here is the configuration file:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync
spec:
  providers:
  - name: keycloak
    keycloak:
      realm: ocp
      credentialsSecret:
        name: keycloak-group-sync
        namespace: group-sync-operator
      caSecret:
        name: rhsso-group-sync
        namespace: group-sync-operator
        key: root-ca.crt
      url: https://rhsso.apps.cluster.fqdn
      loginRealm: ocp
      scope: sub
  schedule: "*/15 * * * *"
```
from the logs of the container "group-sync-operator" i get the error :
```
ERROR          controller-runtime.manager.controller.groupsync Reconciler error      {"reconciler group":  "redhatcop.redhat.io", "reconciler kind": "GroupSync",  "name":   "rhsso-groupsync",  "namespace":  "group-sync-operator",  "error":  "could not get token"} 
github.com/go-logr/zapr.(*zapLogger).Error
               /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*controller.)reconcileHandler
              /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:267
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*controller).processNextWorkItem
             /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*controller).Start.func1.1
             /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContex.func1
            /go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
           /go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
           /go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
           /go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContex
          /go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContex
           /go/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99
```

also my environment is restricted.
