### ISSUE TITLE
ldap - ca ConfigMap error - missing caSecret

### ISSUE THREAD

**Issue by tadamo** [redhat-cop/group-sync-operator#173]
I'm trying to setup a ConfigMap ca, but my process is failing with:

```
ERROR	controller-runtime.manager.controller.groupsync	Reconciler error	{"reconciler group": "redhatcop.redhat.io", "reconciler kind": "GroupSync", "name": "ldap-ad-groupsync", "namespace": "group-sync-operator", "error": "caSecret must be specified when insecure=false", "errorCauses": [{"error": "caSecret must be specified when insecure=false", "errorCauses": [{"error": "caSecret must be specified when insecure=false"}]}]}
```

I read over this section of the docs: https://github.com/redhat-cop/group-sync-operator#ca-certificates

and this issue: https://github.com/redhat-cop/group-sync-operator/issues/158

I believe I should be able to use a ConfigMap instead.

Here's what my configuration looks like:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-ad-groupsync
  namespace: group-sync-operator
spec:
  schedule: '*/30 * * * *'
  providers:
    - ldap:
        groupUIDNameMapping:
            \"CN=foo,OU=Groups,DC=ad,DC=example,DC=edu\": foo
        activeDirectory:
          groupMembershipAttributes:
            - memberOf
          userNameAttributes:
            - sAMAccountName
          usersQuery:
            baseDN: 'DC=ad,DC=example,DC=edu'
            derefAliases: never
            filter: >-
              (&(objectClass=user)(objectCategory=person)(sAMAccountName=*)(department=*))
            scope: sub
            pageSize: 0
        whitelist:
          - 'CN=foo,OU=Groups,DC=ad,DC=example,DC=edu'
        credentialsSecret:
          name: ldap-ad-group-sync-bind
          namespace: group-sync-operator
          kind: Secret
        ca:
          kind: ConfigMap
          name: trusted-ca
          namespace: group-sync-operator
          key: ca-bundle.crt
        url: 'ldaps://ad.example.edu:636'
      name: ldap
```
