### ISSUE TITLE
Sync runs into error for Keycloak 21.0.1

### ISSUE THREAD

**Issue by StefanAnders** [redhat-cop/group-sync-operator#262]
Hi,

I've setup a Keycloak Group Sync for my Keycloak 21.0.1:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync
  namespace: group-sync-operator
spec:
  providers:
    - keycloak:
        credentialsSecret:
          kind: Secret
          name: keycloak-group-sync
          namespace: group-sync-operator
        caSecret:
          name: keycloak-certs
          namespace: group-sync-operator
          key: tls.crt
        loginRealm: master
        prune: false
        realm: openshift
        scope: sub
        url: 'https://<url>/'
      name: keycloak
```

The groups are not synced. 
In the pod's log I'm getting the below error:
```
1.6782706255667229e+09 ERROR Reconciler error {"controller": "groupsync", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "GroupSync", "groupSync": {"name":"keycloak-groupsync","namespace":"group-sync-operator"}, "namespace": "group-sync-operator", "name": "keycloak-groupsync", "reconcileID": "faefa9e8-bf04-4659-8d73-8a4629969b63", "error": "404 Not Found: RESTEASY003210: Could not find resource for full path: https://<url>/auth/realms/master/protocol/openid-connect/token"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
```

The error message states that it can't find my Keycloak under the path **auth/** which is correct since auth isn't used any longer since Keycloak v17.

How can I tell the operator to use the correct token url without auth?
`https://<url>/realms/master/protocol/openid-connect/token`

Thanks in advance
Stefan
