### ISSUE TITLE
 group-sync-operator-controller-manager-metrics-monitor down

### ISSUE THREAD

**Issue by rbaumgar** [redhat-cop/group-sync-operator#322]
due to the the default networkPolicies applied to the namespace of the group-sync-operator, openshift-monitoring cannot access the metrics.
https://docs.openshift.com/container-platform/4.13/networking/network_policy/default-network-policy.html

Apply a networkPolicy like this
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
  namespace: group-sync-operator
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
  policyTypes:
  - Ingress
```

Please update Readme.
