### ISSUE TITLE
0.0.30 is not deployable

### ISSUE THREAD

**Issue by jrmuir** [redhat-cop/group-sync-operator#325]
This is the error we're getting when 0.0.30 tries to replace 0.0.29 or when we try to just install 0.0.30:

```       
install strategy failed: Deployment.apps
"group-sync-operator-controller-manager" is invalid: spec.selector:
Invalid value:
v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"group-sync-operator"},
MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

I assume this is related to the yaml in the operator around this point (starting ~ line 1135):

```
      deployments:
        - label:
            control-plane: group-sync-operator
          name: group-sync-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: group-sync-operator
```

and that the deployment doesn't appreciate having the selector there because the field is immutable.

This happened during an update.  I did try removing the operator completely and reinstalling with .30 but it behaves the same.

Kubernetes version 1.26
