### ISSUE TITLE
Failing to apply filtering Azure Entra Groups in GroupSync CR

### ISSUE THREAD

**Issue by mwohlmutherebc** [redhat-cop/group-sync-operator#334]
We've just set up the GroupSync Operator in OpenShift 4.14 and the synchronization with our Entra directory works generally fine - all groups are synced but we are experiencing an issue:

We've created the following GroupSync object:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: azure-groupsync
  namespace: group-sync-operator
  labels:
    app.kubernetes.io/instance: group-sync-operator
spec:
  excludeInvalidGroupNames: true
  providers:
    - azure:
        credentialsSecret:
          kind: Secret
          name: openid-client-secret
          namespace: openshift-config
      name: azure
  schedule: '*/5 * * * *'
```

We are experiencing the issue, that filtering of groups, either with the "groups" or "baseGroups" parameter inside the azure provider doesn't work, since once the parameter is added, it's immediately removed by the OpenShift cluster from the CR.

E.g.

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: azure-groupsync
  namespace: group-sync-operator
  labels:
    app.kubernetes.io/instance: group-sync-operator
spec:
  excludeInvalidGroupNames: true
  providers:
    - azure:
        credentialsSecret:
          kind: Secret
          name: openid-client-secret
          namespace: openshift-config
      name: azure
      groups:
        - "Group 1"
  schedule: '*/5 * * * *'
```

results in the follwing CR object after saving:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: azure-groupsync
  namespace: group-sync-operator
  labels:
    app.kubernetes.io/instance: group-sync-operator
spec:
  excludeInvalidGroupNames: true
  providers:
    - azure:
        credentialsSecret:
          kind: Secret
          name: openid-client-secret
          namespace: openshift-config
      name: azure
  schedule: '*/5 * * * *'
```

Even tough the CRD shows those parameters should be valid (we also use the version 0.10.0 of the CRD on our cluster): 
https://raw.githubusercontent.com/redhat-cop/group-sync-operator/refs/heads/main/config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml

Is there any prerequisites to use filtering for groups?

Thank you, Michael
