### ISSUE TITLE
We did not see more than 999 results from Graph MS API

### ISSUE THREAD

**Issue by samuano76** [redhat-cop/group-sync-operator#370]
Hello Team,

One of my customer is using GSO to manage Group Sync with AAD, but in the last days they are facing a lack of functionality that we guess to be related to the stage the operator is managing more than 999 rows coming from Graph MS API.

It seems that are not synced more than 999 results coming from Graph MS API, and this lead to some missing users on OCP side.
We seen this line code [1] on GPO Operator that seems to be related to the limits of each query, where you can see the var azurePageSize = int32(999).

GPS consultants team on customer did further tests on GPO Operator version 0.0.31, but same results was observed, such that despite it uses an iterator on API Graph to go trough the list of results with each query that returned 999 record, outcome is to not have more than 999 results in total. 

Following a discussion on OpenShift-SME channel [2] , we agreed that if was further tests showed us other results than that operator do iterate through the list of total results about each queries that returned 999 records, we could open an issue.

Thanks a lot

[1] - https://github.com/redhat-cop/group-sync-operator/blob/main/pkg/syncer/azure.go
[2] - https://groups.google.com/a/redhat.com/g/openshift-sme/c/DOpGRKn9XDg/m/_dYVGDFmAAAJ

**Comment by maborca** [comment]
Hi @sabre1041,
The issue we are facing is that the group in question is assigned to more than 1500 users and the operator is only able to sync on cluster a max of 999 users.

This is the current GroupSync manifest:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: azure-groupsync
  namespace: group-sync-operator
spec:
  providers:
    - azure:
        authorityHost: 'https://login.microsoftonline.com'
        credentialsSecret:
          kind: Secret
          name: azure-group-sync
          namespace: group-sync-operator
        groups:
          - cluster_admin
          - cluster_reader_noprod_mfa
          - TechnicalArchitecture-iniziative
          - backoffice_noprod_mfa
          - backoffice_noprod
          - project_manager_mfa
          - developer_mfa
        prune: false
      name: azure
  schedule: '*/4 * * * *'
```
If we count the users in the OCP group the number of the users is capped at 999:
```
oc get group developer_mfa -o json | jq '.users' | sed '1d;$d' | wc -l
999
```

Let me know if you have more questions.
Thanks!
