### ISSUE TITLE
[azure-ad] usermemebers show as nil

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-cop/group-sync-operator#55]
When I sync the groups, the members are all nil:
```
users:
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
  - <nil>
```

**Comment by sabre1041** [comment]
Can you share provider/config. Looks like it is pulling from a field without a value

**Comment by davidkarlsen** [comment]
```
spec:
  providers:
    - azure:
        credentialsSecret:
          name: azure-group-sync
          namespace: group-sync-operator
      name: azure
```
