### ISSUE TITLE
An error occurred "Not Found" on 0.0.9

### ISSUE THREAD

**Issue by mikehulsman** [redhat-cop/group-sync-operator#70]
Installed the the operator 0.0.9
When trying to configure keycloak I always get the message: an error occurred Not Found
It does not matter if I use the From view or Yaml

My groupsync is defined as:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: groupsync
spec:
  providers:
    - keycloak:
        credentialsSecret:
          name: keycloak-group-sync
          namespace: group-sync-operator
        realm: <realm>
        loginRealm: <login-realm>
        scope: sub
        url: https://xxx.xxx.xxx
```
