### ISSUE TITLE
Console -- Providers->LDAP Provider->"Secret Containing the Credential" improper label class of blacklist 

### ISSUE THREAD

**Issue by pbmoses** [redhat-cop/group-sync-operator#81]
In the Web console  for LDAP -> Provider  the input box presented as "Secret Containing the Credential" is actually the input class for the blacklist resulting in a secret name being placed into the blacklist config. 

```
<label class="" for="root_spec_providers_0_ldap_blacklist_accordion-content">Secret Containing the Credentials</label>
<input class="pf-c-form-control" id="root_spec_providers_0_ldap_blacklist_0" required="" type="text" value="">
```

Resulting in:

```
spec:
  providers:
    - ldap:
        blacklist:
          - testbadconfig
```

I'm not sure where console code is so opening the issue.
